development:
  secret_key_base: 37a9969552babdb7ebfcd4694a8e783149ce2e06317ee38f97b2aa5e35c7e51d2bbc35ea79152e0cbc4c7a3a5afa0780a8314ef47f3c49d40ff0a6c5f63d16fd
  paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  paypal_secret_id: <%= ENV["PAYPAL_SECRET_ID"] %>
test:
  secret_key_base: 37a9969552babdb7ebfcd4694a8e783149ce2e06317ee38f97b2aa5e35c7e51d2bbc35ea79152e0cbc4c7a3a5afa0780a8314ef47f3c49d40ff0a6c5f63d16fd


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    paypal_client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
    paypal_secret_id: <%= ENV["PAYPAL_SECRET_ID"] %>
